### PR TITLE
Datasets V1 and V2 for training of the ventral model

### PR DESCRIPTION
**Pull request by LouisThomasLapointe**
This PR adds tsv files with subjects used to train V1 and V2 models for ventral rootlets segmentation.

### CODE REVIEW

**Comment by valosekj** [comment]
Thanks for opening the PR! 

It seems that a file for V1 is uploaded twice as `V1.tsv` and `V1.tsv.txt`. Can you please keep only the tsv one? i.e., remove `V1.tsv.txt`. (You can use `git rm V1.tsv.txt`)

PS: I took the liberty to add a brief description of your [original comment](https://github.com/ivadomed/model-spinal-rootlets/pull/38#issue-2206606990) (it is a good habit to provide a brief description of what the PR is about).

**Comment by valosekj** [comment]
Looks good now! If the PR is ready to be merged, please assign me as a reviewer, and I will merge it.

**Comment by LouisThomasLapointe** [comment]
It seems that I don't have the necessary access to assign someone as a reviewer (I don't have the menu for it)

**Comment by valosekj** [comment]
I see! No worries, merging!

**Pull request merged**
